server:
  host: 0.0.0.0
  port: 12345

retention:
  xdp_points: 72
  integrity_points: 72

xdp_streams:
  - name: primary-xdp
    endpoint: tcp://103.90.136.195:16666
    topic: ""

integrity_streams:
  - name: primary-integrity_trade
    endpoint: tcp://103.90.136.195:15555
    topic: integrity_trade
